import React from "react";
import Products from "../components/home/Products";

export const metadata = {
  title: {
    default: "All Products",
    template: "%s | Hero Kidz",
  },
  description: "Generated by create next app",
};
const ProductsPage = () => {
  return (
    <div>
      <Products />
    </div>
  );
};

export default ProductsPage;
